<?php
$data=$block->getBrand();
?>
<form method="POST" action="<?= $block->escapeUrl($block->getAddUrl().'id/'.$data->getId())?>" >
    <h3>Brand Details</h3>
    <div>
        <label>Brand Name</label>
        <input name="name" type="text" value="<?= $block->escapeHtml($data['name'] ?? null) ?>"/>
    </div>
    <div>
        <label>Brand Description</label>
        <textarea name="description" ><?= $block->escapeHtml($data['description'] ?? null) ?></textarea>
    </div>
    <button>Submit</button>
</form>
