<?php
/**
 * @var Task\Brand\Block\View $block
 * @var Magento\Framework\Escaper $escaper
 */
$brands = $block->getAllBrand();
?>
<div class="brand-listing">
    <h1>Our Brand List</h1>
    <span>
        <a href="<?= $escaper->escapeUrl($block->getFormUrl())?>"><button>Add New Brand</button></a>
    </span>
    <?php if (count($brands) > 0): ?>
        <table>
            <tr>
                <th><?= $escaper->escapeHtml(__('Id'))?></th>
                <th><?= $escaper->escapeHtml(__('Brand Name')) ?></th>
                <th><?= $escaper->escapeHtml(__('Brand Description')) ?></th>
                <th><?= $escaper->escapeHtml(__('Action')) ?></th>
            </tr>
            <?php foreach ($block->getAllBrand() as $brand): ?>
                <tr>
                    <td><?= $escaper->escapeHtml($brand->getId())?></td>
                    <td><?= $escaper->escapeHtml($brand->getName())?></td>
                    <td><?= $escaper->escapeHtml($brand->getDescription())?></td>
                    <td>
                        <span>
                            <a href="<?=$escaper->escapeHtml($block->getEditUrl().'id/'.$brand->getId())?>"><button>Edit</button></a>
                        </span>
                        <span>
                            <a href="<?=$escaper->escapeHtml($block->getDeleteUrl().'id/'.$brand->getId())?>"><button>Delete</button></a>
                        </span>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    <?php else: ?>
        <h3><?= 'Brand List is Empty'?></h3>
    <?php endif; ?>
</div>
