<div class="wk-customsection" data-bind="scope: 'section'">
    <h3 data-bind="text: customsection().customerdetail"></h3>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "section": {
                        "component": "Prajwal_Assignment6/js/section"
                    }
                }
            }
        }
    }
</script>
